### ISSUE TITLE
same issue

### ISSUE THREAD

**Issue by a298003154** [levymetal/webpack5-double-compile-repro#1]
Then, how can fix this problem
now my webpack version is 5.74.0

**Comment by levymetal** [comment]
@a298003154 This repository is a repro (a minimum reproduction of an issue) and isn't affiliated with webpack. 

You may be able to fix this by specifying an `aggregateTimeout` value of `200` or greater. Reference: https://webpack.js.org/configuration/watch/#watchoptionsaggregatetimeout

If you're having issues with webpack, please comment on the [original issue](https://github.com/webpack/webpack/issues/15206) or open a new issue on the [webpack/webpack](https://github.com/webpack/webpack) repo.
